# 插件基础信息
name: PaopaoerPlugin
main: org.example.paopaoerPlugin1201.PaopaoerPlugin  # 包名+主类名，和代码完全匹配
version: 1.1
author: paopaoer
description: 破土豆服务器1.20.1整活插件
api-version: 1.20.1  # 适配1.20.1版本的核心API版本（必须加）
load: POSTWORLD    # 世界加载后再加载插件，避免报时/烟花功能异常

# 指令注册（包含原有指令+新增/paopaoer主指令）
commands:
  # 原有彩蛋指令
  paopaoerzuishuaile:
    description: 无权限限制的专属彩蛋指令（触发烟花特效）
    usage: /<command>
    aliases: [pprzsl, paopaoerzsl]  # 指令别名
  
  # 新增主指令（支持子指令，语义化提示）
  paopaoer:
    description: PAOPAOER插件主指令（包含时间查询等子功能）
    usage: /<command> <subcommand>  # 用<subcommand>表示“子指令”语义，符合MC指令规范
    aliases: [ppr],[paopaoer]                 # 可选别名，简化输入
    permission: paopaoer.use        # 可选权限节点（默认所有人可用）
    permission-message: §c你没有权限使用该指令！  # 权限不足提示（可选）

# 权限配置（可选，默认所有人都能使用所有指令）
permissions:
  paopaoer.use:
    description: 允许使用/paopaoer主指令及子指令
    default: true  # true=所有玩家可用，op=仅管理员可用
  paopaoerzuishuaile.use:
    description: 允许使用彩蛋指令
    default: true